#!/usr/bin/env python3
import os as _os_timing, time as _time_module
if _os_timing.environ.get('TW_TIMING'):
    import atexit as _atexit
    _t0 = _time_module.perf_counter()

    def _report_timing(_f=__file__):
        elapsed = (_time_module.perf_counter() - _t0) * 1000
        import os.path as _osp
        print(f"[timing] {_osp.basename(_f)}: {elapsed:.1f}ms", file=__import__('sys').stderr)

    _atexit.register(_report_timing)


# ============================================================================
# DEBUG VERSION - Auto-generated by make-awesome.py
# ============================================================================

import os
import sys
from pathlib import Path
from datetime import datetime
# on-add_agenda.py / on-modify_agenda.py
#
# Maintains the edate (effective date) UDA — the earliest of any scheduled,
# due, until, or wait dates present on the task. This lets agenda reports show
# tasks in a single chronological sequence regardless of which date type is set.
#
# https://github.com/linuxcaffe/tw-agenda-hook
#
# Install:
#   cp on-add_agenda.py ~/.task/hooks/
#   ln -s on-add_agenda.py ~/.task/hooks/on-modify_agenda.py
#   chmod +x ~/.task/hooks/on-add_agenda.py
#
# UDA required (or use agenda.rc):
#   uda.edate.type=date
#   uda.edate.label=edate
#
# Retroactive update (existing tasks without edate):
#   task ( +PENDING or +WAITING ) modify +edate_checkall
import json

# Debug configuration (default 0, triggered by tw --debug=2)
DEBUG_MODE = 0

tw_debug_level = os.environ.get('TW_DEBUG', '0')
try:
    tw_debug_level = int(tw_debug_level)
except ValueError:
    tw_debug_level = 0

debug_active = DEBUG_MODE == 1 or tw_debug_level >= 2

def get_log_dir():
    cwd = Path.cwd()
    if (cwd / '.git').exists():
        log_dir = cwd / 'logs' / 'debug'
    else:
        log_dir = Path.home() / '.task' / 'logs' / 'debug'
    log_dir.mkdir(parents=True, exist_ok=True)
    return log_dir

if debug_active:
    DEBUG_LOG_DIR = get_log_dir()
    DEBUG_SESSION_ID = datetime.now().strftime("%Y%m%d_%H%M%S")
    try:
        script_name = Path(__file__).stem
    except:
        script_name = Path(sys.argv[0]).stem if sys.argv else "script"
    DEBUG_LOG_FILE = DEBUG_LOG_DIR / f"{script_name}_debug_{DEBUG_SESSION_ID}.log"
    
    def debug_log(message, level=1):
        if debug_active and tw_debug_level >= level:
            timestamp = datetime.now().strftime("%H:%M:%S.%f")[:-3]
            log_line = f"{timestamp} [DEBUG-{level}] {message}\n"
            with open(DEBUG_LOG_FILE, "a") as f:
                f.write(log_line)
            print(f"\033[34m[DEBUG-{level}]\033[0m {message}", file=sys.stderr)
    
    with open(DEBUG_LOG_FILE, "w") as f:
        f.write("=" * 70 + "\n")
        f.write(f"Debug Session - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"Script: {script_name}\n")
        f.write(f"TW_DEBUG Level: {tw_debug_level}\n")
        f.write("=" * 70 + "\n\n")
    debug_log(f"Debug logging initialized: {DEBUG_LOG_FILE}", 1)
else:
    def debug_log(message, level=1):
        pass

# ============================================================================
# Original Code
# ============================================================================

def create_edate(task):
    # Earliest of any date fields present — TW date strings are YYYYMMDDTHHMMSSZ
    # which sort correctly as plain strings.
    dates = [task[d] for d in ("scheduled", "due", "until", "wait") if d in task]
    if dates:
        task["edate"] = min(dates)
    elif "edate" in task:
        del task["edate"]

    # Retroactive batch update: remove the trigger tag after processing
    if "tags" in task and "edate_checkall" in task["tags"]:
        task["tags"].remove("edate_checkall")

    print(json.dumps(task))


task_line = ""
try:
    old_line = sys.stdin.readline()
    new_line = sys.stdin.readline()
    task_line = (new_line if new_line.strip() else old_line).strip()
    if not task_line:
        sys.exit(0)
    task = json.loads(task_line)
except (json.JSONDecodeError, ValueError) as e:
    print(f"[agenda-edate] JSON parse error: {e}", file=sys.stderr)
    if task_line:
        print(task_line)  # pass through unchanged
    sys.exit(0)

create_edate(task)
